# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26bdf57c0d132bd3658a8610b54d17edfc03862d99ecdfc01f868d9843b25ff0b9c4ed7d1f450c7f836ae7cb02839017a046b439e64516757ccaab020636adf

test:
  secret_key_base: c2d25f003f3404fb3d5fc7f7379c9f454d8c6bb061932b5c6355dda32cb2b31000aa0a74868365e61672792027af02b0b75dfc204396596e7d9f74f54edd5381

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
